length = int(input("Enter the length of the rectangle: "))
width = int(input("Enter the width of the rectangle: "))
print("")
area = 2 * (length * width)
perimeter = 2 * (length + width)
print(f"The area of the rectangle is {area} cm^2")
print()
print(f"The perimeter of the rectangle is {perimeter}cm")
